spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/todo_app?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:todo_user}
    password: ${DB_PASSWORD:todo_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
server:
  port: 8080
